title: League Curriculum
description: League Curriculum Links and Documentation
head:
- - meta
  - content: '#F37121'
    name: theme-color
- - meta
  - content: true
    name: apple-mobile-web-app-capable
- - meta
  - content: black
    name: apple-mobile-web-app-status-bar-style
plugins:
- '@vuepress/plugin-back-to-top'
- '@vuepress/plugin-medium-zoom'
themeConfig:
  displayAllHeaders: true
  repo: 'jointheleague-it/league-curriculum'
  docRepo: 'jointheleague-it/league-curriculum'
  docsDir: 'docs'
  editLinkText: ''
  editLinks: true
  lastUpdated: false
  logo: /assets/Flag.png
  nav:
  - link: /about/
    text: About
  - link: https://jointheleague.org
    text: The LEAGUE
  sidebar:
  - path: /intro
    title: Introduction
  - title: The Lesson Builder
    path: /lb/
    collapsable: false
    children:
      - path: /lb/quickstart.md
        title: Quickstart
      - path: /lb/how_it_works.md
        title: How it Works
      - path: /lb/sources.md
        title: Finding Lessons  
